all:
  children:
    manager:
      hosts:
        swarm-manager:
    worker:
      hosts:
        swarm-worker:
    nginx-lb:
      hosts:
        nginx-lb:

  vars:
    ansible_user: jamal
    ansible_ssh_private_key_file: '~/.ssh/ansible_id_rsa'